### ISSUE TITLE
[BUG] Installation Stuck

### ISSUE THREAD

**Issue by thedinz** [henrywhitaker3/Speedtest-Tracker#172]
**Describe the bug**
The install using docker compose stops or "hangs" at copying latest site files to config

**To Reproduce**
Create docker compose file
Run docker-compose up

**Expected behavior**
A normal and succsessful installation.

**Screenshots**
https://snipboard.io/MOBZmq.jpg

**Context**
 - Docker
 - Speedtest-Tracker Version: Latest

**Comment by henrywhitaker3** [comment]
How long did you leave it? Can take a but longer the first time

**Comment by D4rkSl4ve** [comment]
> **Describe the bug**
> The install using docker compose stops or "hangs" at copying latest site files to config
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Create docker compose file
> Run docker-compose up
> 
> **Expected behavior**
> A normal and succsessful installation.
> 
> **Screenshots**
> https://snipboard.io/MOBZmq.jpg
> 
> **Context**
> 
> * Docker
> * Speedtest-Tracker Version: Latest

Mine had been working for several weeks and for whatever reason (I suspect some kind of update on the container) it stopped working.  It shows a constant restart after about 8 seconds.

**Comment by thedinz** [comment]
> 
> 
> How long did you leave it? Can take a bit longer the first time

It eventually moved past that and got hung up again on another part unfortuently i did not screenshot it, it DID eventually install but holy cow i have never had a docker image take so long so i really assumed it was broken.

However, if i restart that machine instead of just starting the container it appears to do a complete install again, unsure why. I just rebooted the machine and once again speed test is sitting at copying latest config files. Is that normal? To appear to reinstall when stopping and starting the container?

**Comment by D4rkSl4ve** [comment]
> Mine had been working for several weeks and for whatever reason (I suspect some kind of update on the container) it stopped working. It shows a constant restart after about 8 seconds.

Found the fix after reading the log.  Had to do with not having the environment with:  -e OOKLA_EULA_GDPR=true
It's working again.  I guess this wasn't needed for some time!

**Comment by henrywhitaker3** [comment]
So every time it restarts it copies over ant changed site files from the image to your volume and accepts the Ookla EULA & GDPR agreements. No, it's not normal how long it's taking for you, mine takes ~8 seconds to start after first install (should only really take ~30 seconds to install).

Could you try installing without docker compose, just using the standard docker create command in the readme? That way we can see if it's the docker compose stuff causing issues or something else.

**Comment by thedinz** [comment]
I hate to ask but how? I am still new to docker and everyone i speak to tells me to use compose, so i got familiar with compose, I honestly don't know how to install this not using compose while still accepting the license agreement and all that. Sorry probably seems dumb.

**Comment by henrywhitaker3** [comment]
No worries mate, honestly I'm the opposite, have never used compose before and only learnt docker after someone asked me to make an image for this project. 

So the basic command you'd want to run is:

```bash
docker create \
      --name=speedtest \
      -p 8765:80 \
      -v /path/to/data:/config \
      -e PUID=uid \
      -e PGID=gid \
      -e OOKLA_EULA_GDPR=true \
      --restart unless-stopped \
      henrywhitaker3/speedtest-tracker:dev
```

The `-e` argument is used to specify the environment variables:

Where `PUID`/`PGID` is the local user/group id you want the permissions of the data in the volume to be set to. So for the first user you set up on a linux OS that's normally 1000 for both (run `id` in a shell to find the right number). If you don't care about this, you can leave these lines out.

`OOKLA_EULA_GDPR` is used so that you are explicitly accepting the terms of using their speedtest binary when running the container. If you wanted to add a base path, so `domain.com/speedtest` for example, just add `-e BASE_PATH=speedtest` to that command.

The `-v` line is just the path to the folder you want the data to be stored in so that it persists between the container restarting.

The `-p` maps a certain port on the host running docker to the container, so the container uses port 80, this line maps port 8765 to the container's port 80. You can change 8765 to anything you want.

`--restart unless-stopped` sets it so that this conatiner will start when the host reboots.

If you don't want the `dev` image (just has a few more features, still stable but there may be a bug or two), just replace `henrywhitaker3/speedtest-tracker:dev` with `henrywhitaker3/speedtest-tracker`

**Comment by thedinz** [comment]
thank man, ok I will try that, so I had made my own docker-compose file based off that originally and now I see you provided a docker-compose, so I tried that, it at first failed because it sais "logging" was invalid so I removed that whole section and then it ran, but ran just as slowly, in fact, it has not completed yet.

I will try without docker-compose and report back.

**Comment by henrywhitaker3** [comment]
Any progress without compose?

**Comment by sOblivionsCall** [comment]
@thedinz are you running it with some kind of external storage mount at /config? i had major performance issues due to i/o limitation with nfs which caused the container to take ~10 minutes to stand up due to this. Once i removed nfs as a sanity check and used ephemeral storage the container bootstrapped in seconds.

**Comment by henrywhitaker3** [comment]
Closing this as it's been a while since you've responded. Can re-open the issue if you're still having trouble
