### ISSUE TITLE
[BUG] Failure graph not displaying correctly

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#193]
**Describe the bug**
The graph for failure count is not displaying in a coherent way. 
1. The graph makes a massive bump for the entire day instead of small peaks that show the exact time when there was a failure. 
2. the points on the graph show the wrong dates
3. the points show a millisecond result, what is the time a result of if it ended in failure?
4. the points are in odd locations, why are there points in the base of the start and end of the failure 'hump' in the graph? what does this signify?

**To Reproduce**
1. Have a chart of good results over days
2. have a failed result somewhere in the data
3. watch the chart and hover the mouse over points in the graph.

**Expected behavior**
The graph should show where there are failures in a more precise way instead of labeling the whole day as an outage. Maybe have this approach of whole days when looking over a span of 30 days.

The showing of milliseconds is meaningless in the failure. A failure should show as no internet connection. Otherwise, if there is a failure when there is the internet, it should be showing what kind of failure it was. 

**Screenshots**
https://i.imgur.com/f4jcgCa.png
https://i.imgur.com/riXBir9.png
https://i.imgur.com/S8L3q7q.png
https://i.imgur.com/UNxaUci.png

**Context**
 - OS: docker unraid
 - Speedtest-Tracker Version: 1.7.8:Dev

**Comment by henrywhitaker3** [comment]
1. The graph is grouped by day, and shows a percentage rate of failure for each day in the graph, so if you run 9 tests successfully in a day, and 1 failed tests, you'll have a 10% rate of failure.

2. By wrong dates, what do you mean? The dates on the failure graph will not line up with the other graphs in the same place, the other graphs show every test, whereas the failure graph groups an entire day of tests together.

3. The ms on the tooltip should be a `%` symbol, so I need to fix that. 

4. Those bumps shouldn't be there, must be something weird going on with the chart library I'm using. I'll see if I can reproduce those and fix it.

I chose to group failure rate by day as I didn't like a failure registering as 0 on the main graph. I think it may look better to have the failure graph as a bar chart instead of a line graph (so each bar will have 2 sections, failed and succesful tests, sort of like [this](https://www.chartjs.org/samples/latest/charts/bar/stacked.html)). I'm open to suggestions though, if you think there's a better way this could be displayed I'm all ears

**Comment by JesseyWhite** [comment]
1. That's fair I guess, it became confusing because of the other issues. Maybe have the graph label be "Failure Percentage" than just "Failure"

2. look at the dates on this gif, they are not actual dates but just a number counting up every failure. The dates should be in the same location as the ping and download/upload. https://i.imgur.com/IPc7ZII.gif

I think a bar chart would be reasonable.

**Comment by henrywhitaker3** [comment]
What do you think of this?

![2020-07-22_13-36](https://user-images.githubusercontent.com/36062479/88177164-524cb500-cc20-11ea-98dc-56f932f431d7.png)

**Comment by JesseyWhite** [comment]
looks good to me.

**Comment by JesseyWhite** [comment]
Here is another issue with the failure graph
[https://i.imgur.com/e6QADxR.png](https://i.imgur.com/e6QADxR.png)
It is unlikely to matter because it would look like you are reworking it but I thought I would go ahead and mention it.

after purging the config and data, the failure graph does not graph correctly. 

with only a few hours of data, set the showing results for 1 day. the graph doesn't move from its original 7 day

**Comment by JesseyWhite** [comment]
Just something that I have noticed from your picture. You have the year location swapped.

In the failure graph you have the setup of the date as YYYYMMDD but in the speed and ping you have it setup MMDDYYYY

[Ping Dates](https://i.imgur.com/vWyE1Nw.png)
[Failure Dates](https://i.imgur.com/hbUl5a6.png)

**Comment by henrywhitaker3** [comment]
New `dev` image has this graph now. The dates will now display in your local format
