### ISSUE TITLE
[Feature Request] save results to mariadb or something else

### ISSUE THREAD

**Issue by TheGamerFace** [henrywhitaker3/Speedtest-Tracker#439]
It would be great if the results were stored in a sql database instead of the lite database.
In the env specifications I couldnt find anything if this is already possible

**Comment by henrywhitaker3** [comment]
You should be able to override it by setting these env vars:

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=speedtest
DB_USERNAME=root
DB_PASSWORD=
```

Although I haven't tested it

**Comment by TheGamerFace** [comment]
If I add the env variables I can't do a test anymore. GUI shows that a test is running but nothing happens.
Tables and default entries in the SQL are created

**Comment by rubenixnagios** [comment]
Im already trying to store results to mariadb, got the following:

Running database migrations
Migrating: 2020_05_18_211812_create_settings_table
   Illuminate\Database\QueryException 
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'settings' already exists (SQL: create table `settings` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(191) not null, `description` varchar(191) null, `value` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
  at /config/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
    671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|
      +11 vendor frames 
  12  /config/www/database/migrations/2020_05_18_211812_create_settings_table.php:24
      Illuminate\Support\Facades\Facade::__callStatic("create")
      +21 vendor frames 
  34  /config/www/artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))


added beforehand in AppServiceProvider.php:
    public function boot()
    {
		//
	    Schema::defaultStringLength(191);

as per [laravel indications ](https://laravel-news.com/laravel-5-4-key-too-long-error)
otherwise it creates de database but not all tables... anyway cannot get it to work

**Comment by rubenixnagios** [comment]
Migrating: 2020_05_18_211812_create_settings_table
   Illuminate\Database\QueryException
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1 (SQL: insert into `settings` (`name`, `value`, `description`, `updated_at`, `created_at`) values (schedule, 0 * * * *, <p class="d-inline">Set the schedule for speedtests to run using the CRON format. </p><a href="https://crontab.guru/" target="_blank" rel="noopener noreferer">This site</a> can help with formatting., 2021-01-01 21:34:59, 2021-01-01 21:34:59))
  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|
      +20 vendor frames
  21  database/migrations/2020_05_18_211812_create_settings_table.php:43
      Illuminate\Database\Eloquent\Model::__callStatic("create")
      +21 vendor frames
  43  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by rubenixnagios** [comment]
Something to do with Laravel Audit Migration? @henrywhitaker3

**Comment by henrywhitaker3** [comment]
Dropped the ball on this lads, sorry. The env vars were being cleared by php-fpm, so the UI would be using sqlite, and the cli mysql/mariadb.

**Comment by henrywhitaker3** [comment]
Tested and working for me on the latest `dev` or `dev-arm` tags
