### ISSUE TITLE
❓

### ISSUE THREAD

**Issue by Flyy-y** [henrywhitaker3/Speedtest-Tracker#47]
Hello,
Why do you need
### 4 differents technologies for only one page ?
(Python for Speedtest-Cli, PHP, Laravel, React, Node)

 It makes the docker image being **440MB** large. This is a lot.

Please fix the project.

**Comment by henrywhitaker3** [comment]
Not exactly a constructive issue. If you want to re-write it and submit a PR with the changes then feel free.

- Speedtest-cli is a better, more reliable implementation than I could write in PHP
- PHP because you need a language to write the back-end in. I chose PHP.
- Laravel isn't a separate technology from PHP, it's a framework and made development a lot quicker (bearing in mind I only made this to track my own internet speed then decided to make it public later). It also has things like queues and events built-in, so no point in me re-inventing the wheel.
- React, is just a JS framework which made it a lot quicker/easier to write.
- npm is used to install the JS dependencies
