### ISSUE TITLE
Accuracy is way off.

### ISSUE THREAD

**Issue by nickm324** [henrywhitaker3/Speedtest-Tracker#572]
**Describe the bug**
Run the test using single server 2401 for Sugar Hill Georgia US, App says 131mbps, and if I run the speed test from the same server in the browser for Sugar Hill Georgia I get the accurate reading of 460mbps.

**To Reproduce**
Goto settings enter 2401 in the Server field.
Go back to Home, Run test get 131mbps every time.
**Expected behavior**
Go to Speetest.net in browser and use the same server and get the expected 460mbps.

**Screenshots**
Speed Test Tracker. 
![image](https://user-images.githubusercontent.com/6774571/114479087-5a40f080-9bc5-11eb-95f9-0dc6c6fb6ec8.png)

Speedtest.net in Chrome browser on the machine running Speed Test Tracker.
![image](https://user-images.githubusercontent.com/6774571/114479112-69c03980-9bc5-11eb-98c0-1f21a6811f57.png)

**Context**
 - OS: Latest Docker Dev.
 - Speedtest Tracker Version: 1.10.4

**Comment by madtempest** [comment]
This is the fault of the Speedtest binary that is downloaded. It's off by a significant margin for some reason.

**Comment by nickm324** [comment]
So what is the solution to get the binary that works correctly?

**Comment by madtempest** [comment]
Thats a good question - and I think its being talked about in another bug.

**Comment by henrywhitaker3** [comment]
Haven't been able to replicate personally, I think it must be something to do with docker networking. Unless it is an issue with Ookla's binary, in which case, there's nothing I can do (I am planning to add other speedtest providers like fast.com at some point though)

**Comment by birryk** [comment]
I am also off by a large margin.  My speedtest should register around 120 Mbps while it only registers around 38-40 Mbps.

**Comment by chris229** [comment]
I think its due to when running via website, it used multiple servers at the same time from different providers, see under where it says spectrum **+ 3**, when you drill down you see it will be using other servers.
The speedtest CLI only seems to be utilising 1 server at a time and so may not be able to saturate your connection.

**Comment by jeffbyrnes** [comment]
Like @henrywhitaker3 says, I think it may be a Docker networking thing. #479 covers that more specifically; these are probably dupes of each other & one could be closed in favor of the other.

@chris229 also makes an interesting point, b/c if I attempt to run the bin directly from inside the container:

```bash
♠ docker exec -it speedtest bash
root@eac28b95898d:/# /config/www/app/Bin/speedtest 

   Speedtest by Ookla

[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [11] Cannot read from socket: Resource temporarily unavailable
[error] Error: [11] Cannot read from socket: Resource temporarily unavailable
[error] Error: [11] Cannot read from socket: Resource temporarily unavailable
     Server: Comcast - Boston, MA (id = 1774)
        ISP: RCN
    Latency:    10.73 ms   (0.42 ms jitter)
   Download:   218.48 Mbps (data used: 337.7 MB)                               
     Upload:    23.70 Mbps (data used: 42.1 MB)                               
Packet Loss: Not available.
 Result URL: https://www.speedtest.net/result/c/9c69bc67-0d7b-43ef-8336-09a44b8dface
root@eac28b95898d:/# /config/www/app/Bin/speedtest 

   Speedtest by Ookla

[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [11] Cannot read from socket: Resource temporarily unavailable
[error] Error: [110] Cannot open socket: Timeout occurred in connect.
[error] Error: [11] Cannot read from socket: Resource temporarily unavailable
[error] Server Selection - Failed to find a working test server. (NoServers)
```

So there’s definitely some sort of connectivity issue that’s probably warping the results. I’ve also been running [`brennentsmith/internet-speed-logger`](https://github.com/brennentsmith/internet-speed-logger) via bare metal on my Mac instead of in a container, and running directly on bare metal, it gets the speeds I expect.

However, if I run it inside a container, I see the same ⅓ speeds as this project. So it definitely seems like Docker is limiting network throughput. Might have to do w/ bridge mode vs. host mode.
